authentication:
  allow_anonymous_access: true
trees:
  - tree: databroker.mongo_normalized:Tree.from_uri
    path: /
    args:
      uri: mongodb://localhost:27017/mad-bluesky-documents?authSource=admin
