[alias]
manipx = "manipulator.x"
manipy = "manipulator.y"
manipz = "manipulator.z"
manipr = "manipulator.r"
samplex = "manipulator.sx"
sampley = "manipulator.sy"
samplez = "manipulator.sz"
sampler = "manipulator.sr"
energy = "en.energy"
eslit = "Exit_Slit"

[detectors.configuration]
i0 = { threshold = 0.1, description = "Gold Mesh"}
i1 = { threshold = 0.1, description = "Back Diode"}
sc = { threshold = 0.1 }
ref = { threshold = 0.1 }

[detectors.alignment]
indirect = "i1"
direct = "sc"

[detectors.sets.default]
primary = "sc"
normalization = "i0"
reference = "ref"
auxiliary = "tes"

[energy]
energy = "en"
slit = "Exit_Slit"

[manipulators]
sample = "manipulator"
reference = "multimesh"

[shutters]
default = "psh7"